Add statistics
hallovarvara/rslang pull request #108
Opened 2020-07-15 16:01 UTC by Kejno

2020-07-15 16:42 UTC, hallovarvara requested changes
Sprint is broken:

At final page incorrect number of questions guessed and unguessed words.

Incorrect English word (but correct translation and audio). Sprint ended in 5 sec instead of 60 sec.

![image](https://user-images.githubusercontent.com/9438195/87571750-36eb2280-c6d3-11ea-9b22-2849b7a73735.png)

2020-07-15 17:20 UTC, DmitryLebetsky approved these changes

2020-07-15 17:20 UTC, DmitryLebetsky commented on rslang/src/components/Sprint/Sprint.jsx
> +      /* createUserWord */
Don't forget to remove

2020-07-17 14:12 UTC, hallovarvara commented on rslang/src/components/Sprint/Sprint.jsx
> +      /* createUserWord */
fixed

2020-07-17 15:35 UTC, merged