[SPRINT] Sprint start Stepper component
hallovarvara/rslang pull request #114
Opened 2020-07-16 22:15 UTC by Kejno

![sprint1](https://user-images.githubusercontent.com/48594817/87728087-fe2e7480-c7ca-11ea-82d0-255998cf77cd.png)

2020-07-16 23:45 UTC, DmitryLebetsky approved these changes

2020-07-16 23:45 UTC, DmitryLebetsky commented on rslang/src/basicComponents/Notification/NotificationView.jsx
> +    duration = 50000,
You know that duration will be 50 seconds?

2020-07-16 23:45 UTC, DmitryLebetsky commented on rslang/src/components/Savannah/Savannah.jsx
> +  state = JSON.parse(JSON.stringify(initialState))
What is the reason you did it?

2020-07-16 23:45 UTC, DmitryLebetsky commented on rslang/src/components/Savannah/Savannah.jsx
> +    const state = JSON.parse(JSON.stringify(initialState))
What is the reason you did it?

2020-07-16 23:45 UTC, DmitryLebetsky commented on rslang/src/components/Savannah/components/FinishPage/ResultList/ResultList.module.scss
> +  color: #ffffff;
$color-light

2020-07-16 23:45 UTC, DmitryLebetsky commented on rslang/src/components/Savannah/components/FinishPage/ResultList/ResultList.module.scss
> +  background: rgba(161, 240, 69, .7);
It's better to move this colors to constants, like $sprint-color-error, $sprint-color-success

2020-07-16 23:45 UTC, DmitryLebetsky commented on rslang/src/components/Savannah/components/FinishPage/ResultList/ResultList.module.scss
> +  justify-content: flex-start;
Why not to use our mixins? @include flex(column, flex-start, flex-start)

2020-07-16 23:45 UTC, DmitryLebetsky commented on rslang/src/components/Sprint/Components/StartGame/StartGame.jsx
> +  console.log(currentGroup)
Don't forget to remove console.log later

2020-07-16 23:45 UTC, DmitryLebetsky commented on rslang/src/components/Sprint/Components/StartGame/StartGame.jsx
> +          label="Выберите уровень:"
You can take it from our constant text. (text.ru....)

2020-07-16 23:45 UTC, DmitryLebetsky commented on rslang/src/components/Sprint/Sprint.jsx
> +  state = JSON.parse(JSON.stringify(initialState))
Stringify and parse are mutually inverse

2020-07-16 23:45 UTC, DmitryLebetsky commented on rslang/src/components/Sprint/Sprint.jsx
> +    console.log(initialState)
Don't forget to remove

2020-07-16 23:45 UTC, DmitryLebetsky commented on rslang/src/components/Sprint/Sprint.jsx
> +    const state = JSON.parse(JSON.stringify(initialState))
Stringify and parse are mutually inverse

2020-07-16 23:45 UTC, DmitryLebetsky commented on rslang/src/scss/components/_notification.scss
> +    }
Please, don't change general styles. If you want, you can add your class to notification and then change styles by your own selector

2020-07-17 18:50 UTC, hallovarvara requested changes
Please change this element for one like in Prototype:
![image](https://user-images.githubusercontent.com/9438195/87820817-705c9300-c877-11ea-88e6-638f26de32b5.png)

Dima made it in `unmess-repeating-feature`, you can get from there, I'll change styles.

2020-07-17 21:56 UTC, merged